-- 添加warranty_end_date列（如果不存在）
ALTER TABLE issues ADD COLUMN IF NOT EXISTS warranty_end_date DATE DEFAULT NULL COMMENT '保固到期日';

-- 确保其他必要列存在且有正确的类型
ALTER TABLE issues
MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '問題標題',
MODIFY COLUMN description TEXT DEFAULT NULL COMMENT '問題描述',
MODIFY COLUMN source VARCHAR(50) DEFAULT NULL COMMENT '來源',
MODIFY COLUMN issue_type VARCHAR(50) DEFAULT NULL COMMENT '問題類型',
MODIFY COLUMN status VARCHAR(20) DEFAULT 'Pending' COMMENT '狀態',
MODIFY COLUMN assigned_to VARCHAR(50) DEFAULT NULL COMMENT '負責人',
MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間';

-- 确认更改
DESCRIBE issues; 